server:
  port: 8082

spring:
  profiles:
    default: dev
  application:
    name: circuit-breaker
  datasource:
    url: jdbc:postgresql://localhost:5432/circuit-breaker-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# cross-origin for actuator
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
        allowed-headers: '*'