server:
  port: 8083

spring:
  profiles:
    default: dev
  application:
    name: auth

# cross-origin for actuator
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: GET
        allowed-headers: '*'