server:
  port: 8080

spring:
  profiles:
    default: dev
  application:
    name: weather

# cross-origin for actuator
management:
  endpoints:
    web:
      base-path: /weather/actuator
      cors:
        allowed-origins: '*'
        allowed-methods: GET
        allowed-headers: '*'