apiVersion: v1
kind: Service
metadata:
  name: circuit-breaker-svc
spec:
  selector:
    app: circuit-breaker-app
  ports:
    - name: circuit-breaker-svc-port
      protocol: TCP
      nodePort: 30082
      port: 8082
      targetPort: 8082
  type: NodePort