apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-breaker-deployment
  labels:
    app: circuit-breaker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circuit-breaker-app
  template:
    metadata:
      labels:
        app: circuit-breaker-app
    spec:
      containers:
        - name: circuit-breaker-container
          image: cognosce/circuit-breaker-image
          ports:
              - containerPort: 8082
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: circuit-breaker-db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres