apiVersion: v1
kind: Service
metadata:
  name: circuit-breaker-svc
spec:
  selector:
    app: circuit-breaker-app
  ports:
    - name: http-breaker
      protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP