apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-deployment
  labels:
    app: dictionary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-app
  template:
    metadata:
      labels:
        app: dictionary-app
    spec:
      containers:
        - name: dictionary-container
          image: cognosce/dictionary-image
          ports:
              - containerPort: 8081
        - name: redis-db
          image: redis:latest
          ports:
            - containerPort: 6379