apiVersion: v1
kind: Service
metadata:
  name: dictionary-svc
spec:
  selector:
    app: dictionary-app
  ports:
    - name: http-dict
      protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP