apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert-ikbo-24-20-dictionary-deployment
  labels:
    app: dictionary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-app
  template:
    metadata:
      labels:
        app: dictionary-app
    spec:
      containers:
        - name: dictionary-container
          image: cognosce/dictionary-image
          ports:
            - containerPort: 8080