apiVersion: v1
kind: Service
metadata:
  name: dictionary-svc
spec:
  selector:
    app: dictionary-app
  ports:
    - name: dict-svc-port
      protocol: TCP
      # nodePort: 30081
      port: 8081
      targetPort: 8081
  type: ClusterIP